version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: 'topic-test:1:1'
    volumes:
      - /kafka_data:/var/run/docker.sock

  generator-app:
    build:
      context: ../apps/generator
      dockerfile: Dockerfile
    ports:
      - '13000:13000'
    volumes:
      - ../apps/generator:/app
      - /app/node_modules
    environment:
      DB_CONNECTION_STRING: mongodb://root:root@generator-db:27017
  
  generator-db:
    image: mongo 
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  auth-app:
    build:
      context: ../apps/auth
      dockerfile: Dockerfile
    ports:
      - '14000:14000'
    volumes:
      - ../apps/auth:/app
      - /app/node_modules
    environment:
      APP_PORT: 14000
      DB_TYPE: postgres
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: secret
      GENERATOR_APP_URL: http://generator-app:13000

  auth-db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
