name:

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

defaults:
    run:
        working-directory: ./apps/auth

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18
                  cache: npm
            - run: npm install
            - run: npm run test
